[package]
name = "mem-alloc-vec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zkm-sdk = { path = "../../sdk", features = ["snark"] }
#tonic = "0.8.1"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread", "signal"] }
log = { version = "0.4.14", default-features = false }
env_logger = "0.10.0"

[features]
test = []
